select id, ltr.SHORT_VALUE as litera,
CONCAT(CONCAT(SIC_QUESTION.PREFIX_VHOD_DOC, '/'), SIC_QUESTION.SUFIX_VHOD_DOC) as nm,
SIC_QUESTION.REG_DATE, 
SIC_QUESTION.PLAN_EXEC_DATE as plan_date, 
CONCAT(CONCAT(SIC_QUESTION.FAMALY, ' '), SIC_QUESTION.NAME) as otkogo,
nst.FULL_VALUE as noti_stat, 
st.FULL_VALUE as status, 
eorg.SHORT_VALUE as exec_org,
adm.DISPLAYED_NAME as executor
from SIC_QUESTION
LEFT JOIN DESCRIPTOR_VALUE ltr on SIC_QUESTION.LITERA_ID = ltr.DESCRIPTOR_VALUE_ID and ltr.DESCRIPTOR_GROUP_ID = 103
LEFT JOIN DESCRIPTOR_VALUE nst on SIC_QUESTION.NOTI_STATUS_ID = nst.DESCRIPTOR_VALUE_ID and ltr.DESCRIPTOR_GROUP_ID = 147
LEFT JOIN DESCRIPTOR_VALUE st on SIC_QUESTION.STATUS_ID = st.DESCRIPTOR_VALUE_ID and ltr.DESCRIPTOR_GROUP_ID = 146
LEFT JOIN DESCRIPTOR_VALUE eorg on SIC_QUESTION.EXEC_ORG_ID = eorg.DESCRIPTOR_VALUE_ID and ltr.DESCRIPTOR_GROUP_ID = 103
LEFT JOIN ADM_USER adm on SIC_QUESTION.EXECUTOR_ID = adm.USER_ID
order by SIC_QUESTION.REG_DATE DESC;
